FEATURE_NAVIGATION_ON_BOARD = "FEATURE_NAVIGATION_ON_BOARD"
FEATURE_NAVIGATION_VISIBLE_BY_DEFAULT = "FEATURE_NAVIGATION_VISIBLE_BY_DEFAULT"
FEATURE_POSTPONE = "FEATURE_POSTPONE"
FEATURE_SCHEDULER = "FEATURE_SCHEDULER"
